on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        name: Continuous Integration
        permissions:
            contents: read
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6

            - name: Install dependencies
              run: npm install

            - name: Formatting
              run: npm run format:check

            - name: Linting
              run: npm run lint

            - name: Build
              run: npx tsc

            - name: Test
              run: npm test
